development:
  adapter: postgresql
  database: dev_jobs_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: dev_jobs_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: dev_jobs_production
  pool: 5
  timeout: 5000